#sudo chmod 666 /var/run/docker.sock
version: '3.7'
# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  server:
    build: .
    ports:
      - "50051:50051"
    command: python3 server.py
    network_mode: host
#    networks:
#      - net
    depends_on:
      - minio

  minio:
     image: minio/minio:latest
     command: server --console-address ":9001" /data/
     ports:
       - "9000:9000"
       - "9001:9001"
     environment:
       MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin
     volumes:
       - minio-storage:/data
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
       interval: 30s
       timeout: 20s
       retries: 3
     network_mode: host
#     networks:
#       - net

volumes:
 minio-storage:

#networks:
#  net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.20.0.0/16"
#        - gateway: "172.20.0.1"


