# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_service_pb2 as file__service__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/Greeter/UploadFile',
                request_serializer=file__service__pb2.File.SerializeToString,
                response_deserializer=file__service__pb2.MetaData.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/Greeter/DownloadFile',
                request_serializer=file__service__pb2.DownloadRequest.SerializeToString,
                response_deserializer=file__service__pb2.DownloadResponse.FromString,
                )
        self.RemoveFile = channel.unary_unary(
                '/Greeter/RemoveFile',
                request_serializer=file__service__pb2.RemoveFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.RemoveFileResponse.FromString,
                )
        self.GetFileList = channel.unary_unary(
                '/Greeter/GetFileList',
                request_serializer=file__service__pb2.FileListRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileListResponse.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/Greeter/GetFile',
                request_serializer=file__service__pb2.GetFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.MetaData.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def UploadFile(self, request, context):
        """Sends a greeting
        Uploads a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Downloads a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__service__pb2.File.FromString,
                    response_serializer=file__service__pb2.MetaData.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__service__pb2.DownloadRequest.FromString,
                    response_serializer=file__service__pb2.DownloadResponse.SerializeToString,
            ),
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=file__service__pb2.RemoveFileRequest.FromString,
                    response_serializer=file__service__pb2.RemoveFileResponse.SerializeToString,
            ),
            'GetFileList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileList,
                    request_deserializer=file__service__pb2.FileListRequest.FromString,
                    response_serializer=file__service__pb2.FileListResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file__service__pb2.GetFileRequest.FromString,
                    response_serializer=file__service__pb2.MetaData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/UploadFile',
            file__service__pb2.File.SerializeToString,
            file__service__pb2.MetaData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/DownloadFile',
            file__service__pb2.DownloadRequest.SerializeToString,
            file__service__pb2.DownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/RemoveFile',
            file__service__pb2.RemoveFileRequest.SerializeToString,
            file__service__pb2.RemoveFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/GetFileList',
            file__service__pb2.FileListRequest.SerializeToString,
            file__service__pb2.FileListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/GetFile',
            file__service__pb2.GetFileRequest.SerializeToString,
            file__service__pb2.MetaData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
